#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Memory housekeeping: rotation, generated carried-over, audit.

Repo-layer memory governance. Deliberately NO decay/ranking mechanisms
here — expiry and relevance ranking belong to the platform memory
service (AD-9); this layer only moves and measures files.

Commands:
  rotate    move pre-current-month progress entries to progress/YYYY-MM.md
            and prepend a generated "carried over" section (never write
            summaries by hand — generated lists drift, PEP-0 lesson)
  doctor    report sizes, entry counts, threshold breaches
  check     --strict exits 1 when thresholds are exceeded (used by the
            monthly workflow to open a housekeeping issue); without
            --strict prints warnings and exits 0 so the gate never
            deadlocks while memory awaits rotation

Memory root is overridable via MEMORY_ROOT (used by tests).
"""

import argparse
import datetime
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MEMORY = Path(os.environ.get("MEMORY_ROOT", ROOT / "memory"))
PROGRESS = MEMORY / "progress.md"
ACTIVE = MEMORY / "activeContext.md"
ARCHIVE_DIR = MEMORY / "progress"

PROGRESS_SOFT_LINES = 200
ACTIVE_CONTEXT_CAP = 100

ENTRY_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2}) — (.*)$", re.MULTILINE)
ISSUE_REF_RE = re.compile(r"#(\d+)")


def today() -> str:
    return datetime.date.today().isoformat()


def set_updated(head: str, date: str) -> str:
    if re.search(r"^updated: .*$", head, re.MULTILINE):
        return re.sub(r"^updated: .*$", f"updated: {date}", head,
                      count=1, flags=re.MULTILINE)
    return head


def split_progress(text: str) -> tuple[str, list[tuple[str, str, str]]]:
    """Return (head, entries); entries are (date, title, body)."""
    matches = list(ENTRY_RE.finditer(text))
    head = text[: matches[0].start()] if matches else text
    entries: list[tuple[str, str, str]] = []
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        entries.append((m.group(1), m.group(2), text[m.start():end].strip()))
    return head, entries


def carried_over_refs(rotated: list[tuple[str, str, str]]) -> list[int]:
    """Deterministic: union of issue refs in rotated entries and in
    activeContext.md, deduplicated and sorted. Open-state truth lives in
    the issue tracker; this list only answers 'which threads were live'."""
    refs: set[int] = set()
    for _, _, body in rotated:
        refs.update(int(n) for n in ISSUE_REF_RE.findall(body))
    if ACTIVE.exists():
        refs.update(int(n) for n in ISSUE_REF_RE.findall(
            ACTIVE.read_text(encoding="utf-8")))
    return sorted(refs)


def cmd_rotate(_args: argparse.Namespace) -> int:
    if not PROGRESS.exists():
        print(f"ERROR: {PROGRESS} missing", file=sys.stderr)
        return 1
    text = PROGRESS.read_text(encoding="utf-8")
    head, entries = split_progress(text)
    current_month = today()[:7]
    old = [e for e in entries if e[0][:7] < current_month]
    keep = [e for e in entries if e[0][:7] >= current_month]
    if not old:
        print("rotate: nothing older than the current month")
        return 0

    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    by_month: dict[str, list[tuple[str, str, str]]] = {}
    for entry in old:
        by_month.setdefault(entry[0][:7], []).append(entry)
    for month, month_entries in sorted(by_month.items()):
        archive = ARCHIVE_DIR / f"{month}.md"
        if archive.exists():
            print(f"ERROR: {archive} already exists; refusing to overwrite",
                  file=sys.stderr)
            return 1
        body = "\n\n".join(e[2] for e in month_entries)
        archive.write_text(f"# Progress — {month}\n\n{body}\n",
                           encoding="utf-8")
        print(f"archived {len(month_entries)} entries to {archive.name}")

    refs = carried_over_refs(old)
    carried = [f"## {today()} — Carried over", "",
               "<!-- generated by memory_housekeeping.py — do not edit;",
               "open-state truth lives in the issue tracker -->", ""]
    carried += [f"- #{n}" for n in refs] or ["- (no open issue references)"]
    new_text = (set_updated(head, today()).rstrip() + "\n\n"
                + "\n".join(carried) + "\n\n"
                + "\n\n".join(e[2] for e in keep) + ("\n" if keep else ""))
    PROGRESS.write_text(new_text, encoding="utf-8")
    print(f"rotate: progress.md now holds {len(keep)} current-month entries")
    return 0


def collect_findings() -> list[str]:
    findings: list[str] = []
    if PROGRESS.exists():
        lines = PROGRESS.read_text(encoding="utf-8").count("\n")
        if lines > PROGRESS_SOFT_LINES:
            findings.append(
                f"progress.md: {lines} lines > soft threshold "
                f"{PROGRESS_SOFT_LINES} — run memory_housekeeping.py rotate")
    else:
        findings.append("progress.md: missing")
    if ACTIVE.exists():
        lines = ACTIVE.read_text(encoding="utf-8").count("\n")
        if lines > ACTIVE_CONTEXT_CAP:
            findings.append(
                f"activeContext.md: {lines} lines > cap {ACTIVE_CONTEXT_CAP} "
                f"— compress at the next session boundary")
    else:
        findings.append("activeContext.md: missing")
    if ARCHIVE_DIR.exists():
        archives = sorted(ARCHIVE_DIR.glob("*.md"))
        findings.append(f"progress archives: {len(archives)} file(s)")
    return findings


def cmd_doctor(_args: argparse.Namespace) -> int:
    for path in (MEMORY / "projectbrief.md", ACTIVE, PROGRESS):
        if path.exists():
            print(f"{path.name}: {path.read_text(encoding='utf-8').count(chr(10))} lines")
    adr_dir = MEMORY / "decisions"
    if adr_dir.exists():
        print(f"decisions/: {len(list(adr_dir.glob('*.md'))) - 1} ADs")
    findings = collect_findings()
    for finding in findings:
        print(f"NOTE: {finding}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    problems = [f for f in collect_findings()
                if f.startswith(("progress.md:", "activeContext.md:"))
                and "missing" not in f]
    for problem in problems:
        print(f"{'ERROR' if args.strict else 'WARNING'}: {problem}",
              file=sys.stderr)
    if args.strict and problems:
        return 1
    print("housekeeping check: OK" if not problems
          else "housekeeping check: over threshold (non-strict, advisory)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("rotate").set_defaults(func=cmd_rotate)
    sub.add_parser("doctor").set_defaults(func=cmd_doctor)
    p_check = sub.add_parser("check")
    p_check.add_argument("--strict", action="store_true")
    p_check.set_defaults(func=cmd_check)
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    sys.exit(main())
